---
title: "Network Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Set up organization}
#Set up directory
wd_path <- "~/Documents/GitHub/comatsa_network copy 4"
data_path <- "Data/"
save_path <- "Outputs/"

#Load packages
#devtools::install_github('Ecological-Complexity-Lab/emln', force=T)
#devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)
#install_infomap(target_folder = NULL, source = "binary")
#devtools::install_github("manlius/muxViz")
library(infomapecology); library(dplyr); library(vegan);library(igraph);library(muxViz);library(ggridges);library(ggpubr);library(ggpattern);library(scales);library(network);library(GGally);library(ggnet);library(V.PhyloMaker);library(caper);library(MuMIn);library(ggpattern);library(ggpubr)

#Load data
lem_primary <- read.csv(file=paste0( data_path, "lem_primary.csv"))
lem_secondary <- read.csv(file=paste0( data_path, "lem_secondary.csv"))
lem_primary_pred <- read.csv(file=paste0( data_path, "lem_primary_pred.csv"))
lem_secondary_pred <- read.csv(file=paste0( data_path, "lem_secondary_pred.csv"))
lem_primary_fol <- read.csv(file=paste0( data_path, "lem_primary_fol.csv"))
lem_secondary_fol <- read.csv( file=paste0( data_path, "lem_secondary_fol.csv"))
fruit_lengths <- read.csv( file=paste0( data_path, "fruit_lengths.csv"))
lemur_density <- read.csv(file=paste0( data_path,"lemur_density.csv"))
lemur_densities$Estimate <- round(lemur_densities$Estimate, 0)
plant_uses <- read.csv( file=paste0( data_path, "plant_uses2.csv"))
tree_size <- read.csv( file=paste0( data_path, "tree_size.csv"))
wood_density <- read.csv( file=paste0( data_path, "wood_density.csv"))
plant_names <- read.csv(file=paste0( data_path,"plant_names.csv"))
fruit_lengths$FruitLength <- scale(exp(fruit_lengths$FruitLength))
tree_size$DBH <- scale(tree_size$DBH)
wood_density$meanWD <- scale(wood_density$meanWD)
seed_mass <- read.csv( data_path, "seed_mass2.csv") %>% dplyr::select(Genus,mass)
seed_mass$mass <- scale(seed_mass$mass)

```

```{r Data cleaning}

tree_size$Genus[tree_size$Genus=="Mantalania "] <- "Mantalania"

#Clean rownames
rownames(lem_primary) <- lem_primary$X
lem_primary <- lem_primary %>% dplyr::select(-X)
rownames(lem_secondary) <- lem_secondary$X
lem_secondary <- lem_secondary %>% dplyr::select(-X)

rownames(lem_primary_pred) <- lem_primary_pred$X
lem_primary_pred <- lem_primary_pred %>% dplyr::select(-X)
rownames(lem_secondary_pred) <- lem_secondary_pred$X
lem_secondary_pred <- lem_secondary_pred %>% dplyr::select(-X)

rownames(lem_primary_fol) <- lem_primary_fol$X
lem_primary_fol <- lem_primary_fol %>% dplyr::select(-X)
rownames(lem_secondary_fol) <- lem_secondary_fol$X
lem_secondary_fol <- lem_secondary_fol %>% dplyr::select(-X)

#Round to integer
lem_primary <- lem_primary %>% mutate_all(funs(round(., 0)))
lem_secondary <- lem_secondary %>% mutate_all(funs(round(., 0)))
lem_primary_pred <- lem_primary_pred %>% mutate_all(funs(round(., 0)))
lem_secondary_pred <- lem_secondary_pred %>% mutate_all(funs(round(., 0)))  
lem_primary_fol <- lem_primary_fol %>% mutate_all(funs(round(., 0)))
lem_secondary_fol <- lem_secondary_fol %>% mutate_all(funs(round(., 0)))

lem_primary <-  lem_primary %>% dplyr::select(order(colnames(.))) 
lem_secondary <-  lem_secondary %>% dplyr::select(order(colnames(.))) 
lem_primary_pred <-  lem_primary_pred %>% dplyr::select(order(colnames(.))) 
lem_secondary_pred <-  lem_secondary_pred %>% dplyr::select(order(colnames(.)))
lem_primary_fol <-  lem_primary_fol %>% dplyr::select(order(colnames(.))) 
lem_secondary_fol <-  lem_secondary_fol %>% dplyr::select(order(colnames(.)))

#Network into proportions using code adapted from Vitali et al. 2023
primary_disp <- as.data.frame(lem_primary)
secondary_disp  <- as.data.frame(lem_secondary)
Nprim<-primary_disp
Nsec<-secondary_disp
PropNetPrim=ToProp(Nprim) 
PropNetSec=ToProp(Nsec)

primary_pred <- as.data.frame(lem_primary_pred)
secondary_pred  <- as.data.frame(lem_secondary_pred)
Nprim_pred<-primary_pred
Nsec_pred<-secondary_pred
PropNetPrim_pred=ToProp(Nprim_pred) 
PropNetSec_pred=ToProp(Nsec_pred)

primary_fol <- as.data.frame(lem_primary_fol)
secondary_fol  <- as.data.frame(lem_secondary_fol)
Nprim_fol<-primary_fol
Nsec_fol<-secondary_fol
PropNetPrim_fol=ToProp(Nprim_fol) 
PropNetSec_fol=ToProp(Nsec_fol)

```

```{r Plot single-layer networks}
lem_primary_edgelist <- lem_primary%>% mutate(Plants =rownames(lem_primary)) %>%  pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_primary_edgelist$value <- rescale(lem_primary_edgelist$value)*2
net_prim <- network(as.matrix(lem_primary), directed = FALSE, bipartite = TRUE)
disp_primary_weights <-  lem_primary_edgelist$value[lem_primary_edgelist$value!=0]
disp_primary_weights[disp_primary_weights >0 & disp_primary_weights <0.1] <- 0.1

network::set.edge.attribute(net_prim, attrname = "weight",disp_primary_weights)
network::set.vertex.attribute(net_prim, attrname = "Guild", c(rep("Plant", 55),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis","E. rubriventer", "M. lehilahytsara", "C. crossleyi"))

library(GGally)
library(ggplot2)

primary_net_plot <- ggnet2(
  net_prim,
  edge.size = "weight",
  node.size = 3,
  node.color = "Guild",
  palette = c(
    "E. albifrons" = "turquoise",
    "H. occidentalis" = "darkorchid1",
    "L. seali" = "darkblue",
    "A. laniger" = "slateblue2",
    "A. trichotis" = "#56B4E9",
    "E. rubriventer" = "thistle2",
    "M. lehilahytsara" = "blue",
    "C. crossleyi" = "slategrey",
    "Plant" = "darkseagreen4"
  )
) +
  geom_point(aes(color = color), size = 3, color = "black") +
  geom_point(aes(color = color), size = 2.5) +
  scale_color_manual(
    name = "Node", 
    values = c(
      "E. albifrons" = "turquoise",
      "H. occidentalis" = "darkorchid1",
      "L. seali" = "darkblue",
      "A. laniger" = "slateblue2",
      "A. trichotis" = "#56B4E9",
      "E. rubriventer" = "thistle2",
      "M. lehilahytsara" = "blue",
      "C. crossleyi" = "slategrey",
      "Plant" = "darkseagreen4"
    )
  ) +
  guides(color = guide_legend(title = "Node"))  

primary_net_plot


lem_secondary_edgelist <- lem_secondary%>% mutate(Plants =rownames(lem_secondary)) %>% pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_secondary_edgelist$value <- rescale(lem_secondary_edgelist$value)*2
lem_secondary_matrix <- as.matrix(lem_secondary)
net_secondary <- network(lem_secondary_matrix, directed = FALSE, bipartite = TRUE)
disp_secondary_weights <-  lem_secondary_edgelist$value[lem_secondary_edgelist$value!=0]
disp_secondary_weights[disp_secondary_weights >0 & disp_secondary_weights <0.1] <- 0.1
network::set.edge.attribute(net_secondary, attrname = "weight",disp_secondary_weights )

network::set.vertex.attribute(net_secondary, attrname = "Guild", c(rep("Plant", 34),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis", "M. lehilahytsara", "C. crossleyi"))


secondary_net_plot <- ggnet2(net_secondary, edge.size = "weight", node.size = 3, node.color = "Guild", palette = c("E. albifrons"= "turquoise", 
                                          "H. occidentalis"= "darkorchid1", 
                                          "L. seali"="darkblue", 
                                          "A. laniger"="slateblue2", 
                                          "A. trichotis"= "#56B4E9", 
                                          "M. lehilahytsara"="blue",
                                          "C. crossleyi"="slategrey",  "Plant" = "darkgoldenrod2"), label = FALSE)+geom_point(aes(color = color), size = 3, color = "black") + geom_point(aes(color = color), size = 2.5,)+guides(color = FALSE)#+theme(panel.border = element_rect(colour = "grey", fill=NA, size=1))



lem_primary_edgelist_pred <- lem_primary_pred%>% mutate(Plants =rownames(lem_primary_pred)) %>% pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_primary_edgelist_pred$value <- rescale(lem_primary_edgelist_pred$value)*2
lem_primary_matrix_pred <- as.matrix(lem_primary_pred)
net_primary_pred <- network(lem_primary_matrix_pred, directed = FALSE, bipartite = TRUE)
pred_primary_weights <-  lem_primary_edgelist_pred$value[lem_primary_edgelist_pred$value!=0]
pred_primary_weights[pred_primary_weights >0 & pred_primary_weights <0.1] <- 0.1

network::set.edge.attribute(net_primary_pred, attrname = "weight",pred_primary_weights)
network::set.vertex.attribute(net_primary_pred, attrname = "Guild", c(rep("Plant", 32),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis","E. rubriventer", "M. lehilahytsara", "C. crossleyi"))

primary_net_plot_pred <- ggnet2(net_primary_pred, edge.size = "weight", node.size = 3, node.color = "Guild", palette = c("E. albifrons"= "turquoise", 
                                          "H. occidentalis"= "darkorchid1", 
                                          "L. seali"="darkblue", 
                                          "A. laniger"="slateblue2", 
                                          "A. trichotis"= "#56B4E9", 
                                          "E. rubriventer"="thistle2",
                                          "M. lehilahytsara"="blue",
                                          "C. crossleyi"="slategrey", "Plant" = "darkseagreen4"))+geom_point(aes(color = color), size = 3, color = "black") + geom_point(aes(color = color), size = 2.5)+guides(color = FALSE)#+theme(panel.border = element_rect(colour = "grey", fill=NA, size=1))

lem_secondary_edgelist_pred <- lem_secondary_pred%>% mutate(Plants =rownames(lem_secondary_pred)) %>% pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_secondary_edgelist_pred$value <- rescale(lem_secondary_edgelist_pred$value)*2
lem_secondary_matrix_pred <- as.matrix(lem_secondary_pred)
net_secondary_pred <- network(as.matrix(lem_secondary_pred), directed = FALSE, bipartite = TRUE)

pred_secondary_weights <-  lem_secondary_edgelist_pred$value[lem_secondary_edgelist_pred$value!=0]
pred_secondary_weights[pred_secondary_weights >0 &pred_secondary_weights<0.1] <- 0.1

network::set.edge.attribute(net_secondary_pred, attrname = "weight",pred_secondary_weights)
network::set.vertex.attribute(net_secondary_pred, attrname = "Guild", c(rep("Plant", 24),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis", "M. lehilahytsara", "C. crossleyi"))

secondary_net_plot_pred <- ggnet2(net_secondary_pred, edge.size = "weight", node.size = 3, node.color = "Guild", palette = c("E. albifrons"= "turquoise", 
                                          "H. occidentalis"= "darkorchid1", 
                                          "L. seali"="darkblue", 
                                          "A. laniger"="slateblue2", 
                                          "A. trichotis"= "#56B4E9", 
                                          "M. lehilahytsara"="blue",
                                          "C. crossleyi"="slategrey", "Plant" = "darkgoldenrod2"))+geom_point(aes(color = color), size = 3, color = "black") + geom_point(aes(color = color), size = 2.5)+guides(color = FALSE)#+theme(panel.border = element_rect(colour = "grey", fill=NA, size=1))


lem_primary_edgelist_fol <- lem_primary_fol%>% mutate(Plants =rownames(lem_primary_fol)) %>% pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_primary_edgelist_fol$value <- rescale(lem_primary_edgelist_fol$value)*2
lem_primary_matrix_fol <- as.matrix(lem_primary_fol)
net_primary_fol <- network(as.matrix(lem_primary_fol), directed = FALSE, bipartite = TRUE)

fol_primary_weights <-  lem_primary_edgelist_fol$value[lem_primary_edgelist_fol$value!=0]
fol_primary_weights[fol_primary_weights >0 &fol_primary_weights<0.1] <- 0.1

network::set.edge.attribute(net_primary_fol, attrname = "weight",fol_primary_weights)
network::set.vertex.attribute(net_primary_fol, attrname = "Guild", c(rep("Plant", 37),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis","P. candidus", "E. rubriventer", "M. lehilahytsara", "C. crossleyi"))

primary_net_plot_fol <- ggnet2(net_primary_fol, edge.size = "weight", node.size = 3, node.color = "Guild", palette = c("E. albifrons"= "turquoise", 
                                          "H. occidentalis"= "darkorchid1", 
                                          "L. seali"="darkblue", 
                                          "A. laniger"="slateblue2", 
                                          "A. trichotis"= "#56B4E9", 
                                          "P. candidus" = "coral2",
                                          "E. rubriventer" = "thistle2",
                                          "M. lehilahytsara"="blue",
                                          "C. crossleyi"="slategrey", "Plant" = "darkseagreen4"))+geom_point(aes(color = color), size = 3, color = "black") + geom_point(aes(color = color), size = 2.5)+guides(color = FALSE)#+theme(panel.border = element_rect(colour = "grey", fill=NA, size=1))

lem_secondary_edgelist_fol <- lem_secondary_fol %>% mutate(Plants =rownames(lem_secondary_fol)) %>% pivot_longer(cols=Akomba:Tsitsihy)%>% rename(Lemur=name)
lem_secondary_edgelist_fol$value <- rescale(lem_secondary_edgelist_fol$value)*2
net_secondary_fol <- network(as.matrix(lem_secondary_fol), directed = FALSE, bipartite = TRUE)

fol_secondary_weights <-  lem_secondary_edgelist_fol$value[lem_secondary_edgelist_fol$value!=0]
fol_secondary_weights[fol_secondary_weights >0 &fol_secondary_weights<0.1] <- 0.1

network::set.edge.attribute(net_secondary_fol, attrname = "weight",fol_secondary_weights)
network::set.vertex.attribute(net_secondary_fol, attrname = "Guild", c(rep("Plant", 17),"E. albifrons", "H. occidentalis", "L. seali", "A. laniger", "A. trichotis","M. lehilahytsara", "C. crossleyi"))

secondary_net_plot_fol <- ggnet2(net_secondary_fol, edge.size = "weight", node.size = 3, node.color = "Guild", palette = c("E. albifrons"= "turquoise", 
                                          "H. occidentalis"= "darkorchid1", 
                                          "L. seali"="darkblue", 
                                          "A. laniger"="slateblue2", 
                                          "A. trichotis"= "#56B4E9", 
                                          "M. lehilahytsara"="blue",
                                          "C. crossleyi"="slategrey",  "Plant" = "darkgoldenrod2"), label = FALSE)+geom_point(aes(color = color), size = 3, color = "black") + geom_point(aes(color = color), size = 2.5,)+guides(color = FALSE)#+theme(panel.border = element_rect(colour = "grey", fill=NA, size=1))

single_plots <- ggarrange(primary_net_plot,secondary_net_plot,
                          primary_net_plot_pred,secondary_net_plot_pred, 
                          primary_net_plot_fol, secondary_net_plot_fol,labels = c(" a", " b", " c", " d", " e", " f"),font.label = list(size = 16, color = "black"), common.legend = TRUE, ncol=2, nrow=3)


```

```{r PageRank Centrality: Single-layer}
#Single Layer
centrality_lem_primary <- igraph::graph_from_incidence_matrix(PropNetPrim, weighted = TRUE)
centrality_lem_secondary <- igraph::graph_from_incidence_matrix(PropNetSec, weighted = TRUE)
centrality_lem_primary_pred <- igraph::graph_from_incidence_matrix(PropNetPrim_pred, weighted = TRUE)
centrality_lem_secondary_pred <- igraph::graph_from_incidence_matrix(PropNetSec_pred, weighted = TRUE)
centrality_lem_primary_fol <- igraph::graph_from_incidence_matrix(PropNetPrim_fol, weighted = TRUE)
centrality_lem_secondary_fol <- igraph::graph_from_incidence_matrix(PropNetSec_fol, weighted = TRUE)

pr_lem_primary <- as.data.frame(page_rank(centrality_lem_primary)$vector)
pr_lem_secondary <- as.data.frame(page_rank(centrality_lem_secondary)$vector)
pr_lem_primary_pred <- as.data.frame(page_rank(centrality_lem_primary_pred)$vector)
pr_lem_secondary_pred <-as.data.frame(page_rank(centrality_lem_secondary_pred)$vector)
pr_lem_primary_fol <- as.data.frame(page_rank(centrality_lem_primary_fol)$vector)
pr_lem_secondary_fol <- as.data.frame(page_rank(centrality_lem_secondary_fol)$vector)

pr_lem_primary$Node <- rownames(pr_lem_primary)
colnames(pr_lem_primary)[1] <- "PageRank"
pr_lem_secondary$Node <- rownames(pr_lem_secondary)
colnames(pr_lem_secondary)[1] <- "PageRank"
pr_lem_primary_pred$Node <- rownames(pr_lem_primary_pred)
colnames(pr_lem_primary_pred)[1] <- "PageRank"
pr_lem_secondary_pred$Node <- rownames(pr_lem_secondary_pred)
colnames(pr_lem_secondary_pred)[1] <- "PageRank"
pr_lem_primary_fol$Node <- rownames(pr_lem_primary_fol)
colnames(pr_lem_primary_fol)[1] <- "PageRank"
pr_lem_secondary_fol$Node <- rownames(pr_lem_secondary_fol)
colnames(pr_lem_secondary_fol)[1] <- "PageRank"

pr_lem_primary$Habitat <- "Primary"
pr_lem_primary$Interaction <- "Dispersal"
pr_lem_secondary$Habitat <- "secondary"
pr_lem_secondary$Interaction <- "Dispersal"
pr_lem_primary_pred$Habitat <- "Primary"
pr_lem_primary_pred$Interaction <- "Predation"
pr_lem_secondary_pred$Habitat <- "secondary"
pr_lem_secondary_pred$Interaction <- "Predation"
pr_lem_primary_fol$Habitat <- "Primary"
pr_lem_primary_fol$Interaction <- "Folivory"
pr_lem_secondary_fol$Habitat <- "secondary"
pr_lem_secondary_fol$Interaction <- "Folivory"

pagerank_df <- rbind(pr_lem_primary, pr_lem_secondary,
                    pr_lem_primary_pred, pr_lem_secondary_pred,
                    pr_lem_primary_fol, pr_lem_secondary_fol)

centrality_single_lemur <- pagerank_df  %>% filter(Node== "Hay.hay"| Node=="Akomba"|Node=="Tongono"|Node=="Simpona"|Node=="Fotsife"|Node=="Fitsidika"|Node=="Tsidy"|Node=="Tsitsihy"|Node=="Kandrandra"| Node=="Bokombolo")

centrality_single_plant <- pagerank_df  %>% filter(Node!= "Hay.hay", Node!="Akomba",Node!="Tongono",Node!="Simpona",Node!="Fotsife",Node!="Fitsidika",Node!="Tsidy",Node!="Tsitsihy",Node!="Kandrandra", Node!="Bokombolo")



```

```{r PageRank Centrality: Multilayer}
#DISPERSAL
SupraAdjacencyMatrix <- as.data.frame(Multi_object_disp$extended)
colnames(SupraAdjacencyMatrix) <- c("layer.from", "node.from", "layer.to", "node.to", "weight")
SupraAdjacencyMatrix  <- SupraAdjacencyMatrix %>% dplyr::select(node.from, layer.from, node.to, layer.to, weight)%>% drop_na()
length(unique(Multi_object_disp$extended$node_to))
SupraAdjacencyMatrix$layer.to[SupraAdjacencyMatrix$layer.to=="Primary"] <- 1
SupraAdjacencyMatrix$layer.from[SupraAdjacencyMatrix$layer.from=="Primary"] <- 1
SupraAdjacencyMatrix$layer.to[SupraAdjacencyMatrix$layer.to=="Secondary"] <- 2
SupraAdjacencyMatrix$layer.from[SupraAdjacencyMatrix$layer.from=="Secondary"] <- 2
SupraAdjacencyMatrix <- SupraAdjacencyMatrix %>% rename(node_name = node.from) 

SupraAdjacencyMatrix <- left_join(SupraAdjacencyMatrix, Multi_object_disp$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.from = node_id)
SupraAdjacencyMatrix <- SupraAdjacencyMatrix %>% rename(node_name = node.to) 

Node_names <- left_join(SupraAdjacencyMatrix, Multi_object_disp$state_nodes[,-1], by="node_name")%>% dplyr::select(node_name, node_id)%>%distinct()%>% rename(Node= node_id)
Node_names$Node <- as.factor(Node_names$Node)

SupraAdjacencyMatrix <- left_join(SupraAdjacencyMatrix, Multi_object_disp$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.to = node_id)%>%dplyr::select(node.from, layer.from, node.to, layer.to, weight) %>% distinct()

SupraAdjacencyMatrix$layer.from <- as.numeric(SupraAdjacencyMatrix$layer.from)
SupraAdjacencyMatrix$layer.to <- as.numeric(SupraAdjacencyMatrix$layer.to)
SupraAdjacencyMatrix[471,] <- c(57,1, 57,2,0)

SupraAdjacencyMatrix  <- BuildSupraAdjacencyMatrixFromExtendedEdgelist(
  mEdges = SupraAdjacencyMatrix,
  Layers= 2,
  Nodes= 68,
  isDirected= FALSE
)

centrality <- GetMultiPageRankCentrality(SupraAdjacencyMatrix, Layers=2, Nodes=68)
centrality.df <- as.data.frame(centrality)
centrality.df$Node <- rownames(centrality.df)
centrality.df2 <- left_join(centrality.df, Node_names)
centrality.df2$node_name[is.na(centrality.df2$node_name)] <- "Tongono"

centrality_lemur <- centrality.df2  %>% filter(node_name=="Akomba"|node_name=="Tongono"|node_name=="Simpona"|node_name=="Fotsife"|node_name=="Fitsidika"|node_name=="Tsidy"|node_name=="Tsitsihy"|node_name=="Kandrandra"| node_name=="Bokombolo")%>% dplyr::select(V1,node_name)
centrality_lemur$Habitat <- "Multilayer"
centrality_lemur$Interaction <- "Dispersal"
colnames(centrality_lemur)<- c("PageRank", "Node", "Habitat", "Interaction")

centrality_plant <- centrality.df2  %>% filter(node_name!="Akomba",node_name!="Tongono",node_name!="Simpona",node_name!="Fotsife",node_name!="Fitsidika",node_name!="Tsidy",node_name!="Tsitsihy",node_name!="Kandrandra", node_name!="Bokombolo")%>% dplyr::select(V1,node_name)
centrality_plant$Habitat <- "Multilayer"
centrality_plant$Interaction <- "Dispersal"
colnames(centrality_plant)<- c("PageRank", "Node", "Habitat", "Interaction")



#PREDATION
SupraAdjacencyMatrix_pred <- as.data.frame(Multi_object_pred$extended)
colnames(SupraAdjacencyMatrix_pred) <- c("layer.from", "node.from", "layer.to", "node.to", "weight")
SupraAdjacencyMatrix_pred  <- SupraAdjacencyMatrix_pred %>% dplyr::select(node.from, layer.from, node.to, layer.to, weight)%>% drop_na()
length(unique(Multi_object_pred$extended$node_to))
SupraAdjacencyMatrix_pred$layer.to[SupraAdjacencyMatrix_pred$layer.to=="Primary"] <- 1
SupraAdjacencyMatrix_pred$layer.from[SupraAdjacencyMatrix_pred$layer.from=="Primary"] <- 1
SupraAdjacencyMatrix_pred$layer.to[SupraAdjacencyMatrix_pred$layer.to=="Secondary"] <- 2
SupraAdjacencyMatrix_pred$layer.from[SupraAdjacencyMatrix_pred$layer.from=="Secondary"] <- 2
SupraAdjacencyMatrix_pred <- SupraAdjacencyMatrix_pred %>% rename(node_name = node.from) 

SupraAdjacencyMatrix_pred <- left_join(SupraAdjacencyMatrix_pred, Multi_object_pred$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.from = node_id)
SupraAdjacencyMatrix_pred <- SupraAdjacencyMatrix_pred %>% rename(node_name = node.to) 

Node_names <- left_join(SupraAdjacencyMatrix_pred, Multi_object_pred$state_nodes[,-1], by="node_name")%>% dplyr::select(node_name, node_id)%>%distinct()%>% rename(Node= node_id)
Node_names$Node <- as.factor(Node_names$Node)

SupraAdjacencyMatrix_pred <- left_join(SupraAdjacencyMatrix_pred, Multi_object_pred$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.to = node_id)%>%dplyr::select(node.from, layer.from, node.to, layer.to, weight) %>% distinct()
SupraAdjacencyMatrix_pred$layer.from <- as.numeric(SupraAdjacencyMatrix_pred$layer.from)
SupraAdjacencyMatrix_pred$layer.to <- as.numeric(SupraAdjacencyMatrix_pred$layer.to)
SupraAdjacencyMatrix_pred[244,] <- c(33,1, 33,2,0)
SupraAdjacencyMatrix_pred[245,] <- c(38,1, 38,2,0)

SupraAdjacencyMatrix_pred  <- BuildSupraAdjacencyMatrixFromExtendedEdgelist(
  mEdges = SupraAdjacencyMatrix_pred,
  Layers= 2,
  Nodes= 46,
  isDirected= FALSE
)

centrality_pred <- GetMultiPageRankCentrality(SupraAdjacencyMatrix_pred, Layers=2, Nodes=46)
centrality.df_pred <- as.data.frame(centrality_pred)
centrality.df_pred$Node <- rownames(centrality.df_pred)
centrality.df2_pred <- left_join(centrality.df_pred, Node_names)
centrality.df2_pred$node_name[centrality.df2_pred$Node==33] <- "Simpona"
centrality.df2_pred$node_name[centrality.df2_pred$Node==38] <- "Tongono"

centrality_lemur_pred <- centrality.df2_pred  %>% filter(node_name=="Akomba"|node_name=="Tongono"|node_name=="Simpona"|node_name=="Fotsife"|node_name=="Fitsidika"|node_name=="Tsidy"|node_name=="Tsitsihy"|node_name=="Kandrandra"| node_name=="Bokombolo"| node_name=="Simpona")%>% dplyr::select(V1,node_name)
centrality_lemur_pred$Habitat <- "Multilayer"
centrality_lemur_pred$Interaction <- "Predation"
colnames(centrality_lemur_pred)<- c("PageRank", "Node", "Habitat", "Interaction")

centrality_plant_pred <- centrality.df2_pred  %>% filter(node_name!="Akomba"|node_name!="Tongono"|node_name!="Simpona"|node_name!="Fotsife"|node_name!="Fitsidika"|node_name!="Tsidy"|node_name!="Tsitsihy"|node_name!="Kandrandra"| node_name!="Bokombolo")%>% dplyr::select(V1,node_name)
centrality_plant_pred$Habitat <- "Multilayer"
centrality_plant_pred$Interaction <- "Predation"
colnames(centrality_plant_pred)<- c("PageRank", "Node", "Habitat", "Interaction")



#FOLIVORY
SupraAdjacencyMatrix_fol <- as.data.frame(Multi_object_fol$extended)
colnames(SupraAdjacencyMatrix_fol) <- c("layer.from", "node.from", "layer.to", "node.to", "weight")
SupraAdjacencyMatrix_fol  <- SupraAdjacencyMatrix_fol %>% dplyr::select(node.from, layer.from, node.to, layer.to, weight)%>% drop_na()
length(unique(Multi_object_fol$extended$node_to))
SupraAdjacencyMatrix_fol$layer.to[SupraAdjacencyMatrix_fol$layer.to=="Primary"] <- 1
SupraAdjacencyMatrix_fol$layer.from[SupraAdjacencyMatrix_fol$layer.from=="Primary"] <- 1
SupraAdjacencyMatrix_fol$layer.to[SupraAdjacencyMatrix_fol$layer.to=="Secondary"] <- 2
SupraAdjacencyMatrix_fol$layer.from[SupraAdjacencyMatrix_fol$layer.from=="Secondary"] <- 2
SupraAdjacencyMatrix_fol <- SupraAdjacencyMatrix_fol %>% rename(node_name = node.from) 

SupraAdjacencyMatrix_fol <- left_join(SupraAdjacencyMatrix_fol, Multi_object_fol$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.from = node_id)
SupraAdjacencyMatrix_fol <- SupraAdjacencyMatrix_fol %>% rename(node_name = node.to) 

Node_names <- left_join(SupraAdjacencyMatrix_fol, Multi_object_fol$state_nodes[,-1], by="node_name")%>% dplyr::select(node_name, node_id)%>%distinct()%>% rename(Node= node_id)
Node_names$Node <- as.factor(Node_names$Node)

SupraAdjacencyMatrix_fol <- left_join(SupraAdjacencyMatrix_fol, Multi_object_fol$state_nodes[,-1], by="node_name") %>% dplyr::select(-layer_name, -node_name) %>% rename(node.to = node_id)%>%dplyr::select(node.from, layer.from, node.to, layer.to, weight) %>% distinct()
SupraAdjacencyMatrix_fol$layer.from <- as.numeric(SupraAdjacencyMatrix_fol$layer.from)
SupraAdjacencyMatrix_fol$layer.to <- as.numeric(SupraAdjacencyMatrix_fol$layer.to)
SupraAdjacencyMatrix_fol[125,] <- c(38,1, 38,2,0)
SupraAdjacencyMatrix_fol[126,] <- c(43,1, 43,2,0)

SupraAdjacencyMatrix_fol  <- BuildSupraAdjacencyMatrixFromExtendedEdgelist(
  mEdges = SupraAdjacencyMatrix_fol,
  Layers= 2,
  Nodes= 48,
  isDirected= FALSE
)

centrality_fol <- GetMultiPageRankCentrality(SupraAdjacencyMatrix_fol, Layers=2, Nodes=48)
centrality.df_fol <- as.data.frame(centrality_fol)
centrality.df_fol$Node <- rownames(centrality.df_fol)
centrality.df2_fol <- left_join(centrality.df_fol, Node_names)
centrality.df2_fol$node_name[centrality.df2_fol$Node==38] <- "Simpona"
centrality.df2_fol$node_name[centrality.df2_fol$Node==43] <- "Tongono"

centrality_lemur_fol <- centrality.df2_fol  %>% filter(node_name=="Akomba"|node_name=="Tongono"|node_name=="Simpona"|node_name=="Fotsife"|node_name=="Fitsidika"|node_name=="Tsidy"|node_name=="Tsitsihy"|node_name=="Kandrandra"| node_name=="Bokombolo"| node_name=="Simpona")%>% dplyr::select(V1,node_name)
centrality_lemur_fol$Habitat <- "Multilayer"
centrality_lemur_fol$Interaction <- "Folivory"
colnames(centrality_lemur_fol)<- c("PageRank", "Node", "Habitat", "Interaction")

centrality_plant_fol <- centrality.df2_fol%>%filter(node_name!="Akomba",node_name!="Tongono",node_name!="Simpona",node_name!="Fotsife",node_name!="Fitsidika",node_name!="Tsidy",node_name!="Tsitsihy",node_name!="Kandrandra",node_name!="Bokombolo")%>% dplyr::select(V1,node_name)
centrality_plant_fol$Habitat <- "Multilayer"
centrality_plant_fol$Interaction <- "Folivory"
colnames(centrality_plant_fol)<- c("PageRank", "Node", "Habitat", "Interaction")

```

```{r Plotting PageRank Centrality}

#Combine dataframes
centrality_multi_plant <- rbind(centrality_plant, centrality_plant_pred, centrality_plant_fol)
centrality_multi_lemur <- rbind(centrality_lemur, centrality_lemur_pred, centrality_lemur_fol)
centrality_total_plant <- rbind(centrality_multi_plant, centrality_single_plant)
centrality_total_lemur <- rbind(centrality_multi_lemur, centrality_single_lemur)

centrality_total_plant <- centrality_total_plant %>% group_by(Node, Habitat, Interaction,) %>% summarise(PageRank=mean(PageRank))%>%filter(Node!="Akomba",Node!="Tongono",Node!="Simpona",Node!="Fotsife",Node!="Fitsidika",Node!="Tsidy",Node!="Tsitsihy",Node!="Kandrandra",Node!="Bokombolo")

centrality_total_plant$Interaction[centrality_total_plant$Interaction=="Folivory"] <- "Herbivory"

centrality_total_plant$Interaction <- factor(centrality_total_plant$Interaction, levels = c("Dispersal", "Predation", "Herbivory"))
centrality_total_plant$Habitat[centrality_total_plant$Habitat=="secondary"] <- "Secondary"

centrality_total_plant_prop <- centrality_total_plant %>% group_by(Habitat, Interaction) %>% summarise(TotalPageRank = sum(PageRank))

centrality_total_plant2 <- centrality_total_plant
centrality_total_plant2 <- left_join(centrality_total_plant2, centrality_total_plant_prop, by =c("Habitat", "Interaction"))%>% mutate(PropPageRank = PageRank/ TotalPageRank)
 
centrality_total_plant2$Habitat <- factor(centrality_total_plant2$Habitat, levels = c("Multilayer","Secondary", "Primary"))


pagerank_plants <- ggplot(data=centrality_total_plant2, aes(x= reorder(Node, PropPageRank), y=PropPageRank, fill=Habitat))+
  geom_bar(position="stack", stat="identity")+
  theme_classic()+
  coord_flip()+
  xlab("Tree Genus")+
  ylab("Proportion Total PageRank per Land Use")+
    facet_wrap(~Interaction)+
  scale_fill_manual(values = c("grey", "lightgoldenrod","darkseagreen3"), name = "Land Use Type")+
  theme(legend.position="bottom")

centrality_total_lemur$Node[centrality_total_lemur$Node=="Akomba"]<- "E. albifrons"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Bokombolo"]<- "H. occidentalis"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Kandrandra"]<- "A. trichotis"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Fotsife"]<- "A. laniger"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Fitsidika"]<- "L. seali"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Simpona"]<- "P. candidus"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Tsidy"]<- "M. lehilahytsara"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Tsitsihy"]<- "C. crossleyi"
centrality_total_lemur$Node[centrality_total_lemur$Node=="Tongono"]<- "E. rubriventer"

centrality_total_lemur$Interaction[centrality_total_lemur$Interaction=="Folivory"]<- "Herbivory"

centrality_total_lemur$Interaction <- factor(centrality_total_lemur$Interaction, levels = c("Dispersal", "Predation", "Herbivory"))
centrality_total_lemur$Habitat[centrality_total_lemur$Habitat=="secondary"] <- "Secondary"

centrality_total_lemur$Habitat[centrality_total_lemur$Habitat=="Both"] <- "Multilayer"

centrality_total_lemur_prop <- centrality_total_lemur %>% group_by(Habitat, Interaction) %>% summarise(TotalPageRank = sum(PageRank))

centrality_total_lemur2 <- centrality_total_lemur
centrality_total_lemur2 <- left_join(centrality_total_lemur, centrality_total_lemur_prop, by =c("Habitat", "Interaction"))%>% mutate(PropPageRank = PageRank/ TotalPageRank)

centrality_total_lemur2$Habitat <- factor(centrality_total_lemur2$Habitat, levels = c( "Multilayer","Secondary", "Primary"))

pagerank_lemurs <- ggplot(data=centrality_total_lemur2, aes(x= reorder(Node, PropPageRank), y=PropPageRank, fill=Habitat))+
  geom_bar(position="stack", stat="identity")+
  theme_classic()+
  coord_flip()+
  xlab("Lemur Species")+
  ylab("Proportion Total PageRank per Land Use")+
  facet_wrap(~Interaction)+
  scale_fill_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"), name = "Land Use Type")+
  theme(legend.position="bottom")
#MAKE PROPORTION OF PAGERANK

pagerank_species <- ggarrange(pagerank_lemurs,pagerank_plants,  labels=c("a", "b"), common.legend = TRUE)

centrality_total_plant3 <- centrality_total_plant2 %>% pivot_wider(names_from = Habitat, values_from = PageRank)

lemur_centrality <- centrality_total_lemur2 %>% dplyr::select(Node, PageRank, Habitat, Interaction) %>% pivot_wider(values_from = PageRank, names_from = Interaction) %>% dplyr::select(Habitat, Node, Dispersal, Predation, Folivory) %>% mutate(Dispersal = round(Dispersal,3),Predation = round(Predation,3),Folivory = round(Folivory,3))

write.csv(lemur_centrality, file=paste0(save_path, "lemur_centrality.csv"))


tree_centrality_multilayer <- centrality_total_plant2 %>%filter(Habitat=="Multilayer")%>% dplyr::select(Node, PageRank, Habitat, Interaction) %>% pivot_wider(values_from = PageRank, names_from = Interaction) %>% dplyr::select(Habitat, Node, Dispersal, Predation, Folivory) %>% mutate(Dispersal = round(Dispersal,3),Predation = round(Predation,3),Folivory = round(Folivory,3))

tree_centrality_primary <- centrality_total_plant2 %>%filter(Habitat=="Primary")%>% dplyr::select(Node, PageRank, Habitat, Interaction) %>% pivot_wider(values_from = PageRank, names_from = Interaction) %>% dplyr::select(Habitat, Node, Dispersal, Predation, Folivory) %>% mutate(Dispersal = round(Dispersal,3),Predation = round(Predation,3),Folivory = round(Folivory,3)) 

tree_centrality_secondary <- centrality_total_plant2 %>%filter(Habitat=="Secondary")%>% dplyr::select(Node, PageRank, Habitat, Interaction) %>% pivot_wider(values_from = PageRank, names_from = Interaction) %>% dplyr::select(Habitat, Node, Dispersal, Predation, Folivory) %>% mutate(Dispersal = round(Dispersal,3),Predation = round(Predation,3),Folivory = round(Folivory,3)) 


write.csv(tree_centrality_multilayer, file=paste0(save_path, "tree_centrality_multilayer.csv"))
write.csv(tree_centrality_primary, file=paste0(save_path, "tree_centrality_primary.csv"))
write.csv(tree_centrality_secondary, file=paste0(save_path, "tree_centrality_secondary.csv"))

```

```{r Plant Traits: Human Use}

plant_uses$UseSum <- plant_uses$UseSum/81

#HUMAN USES
#Building/ cleaning dataframes
centrality_plant2 <- centrality_plant %>% rename("Genus"="Node") #%>% group_by(Node) %>% summarise(PageRank=sum(PageRank))
plant_uses2 <- plant_uses
plant_uses3 <- left_join(centrality_plant2, plant_uses2, by="Genus")
centrality_single_plant2 <- centrality_single_plant %>% rename(Genus = Node)
plant_uses_prim <- left_join(centrality_single_plant2, plant_uses2, by="Genus")
centrality_plant2_pred<- centrality_plant_pred %>% group_by(Node) %>% rename("Genus"="Node")
plant_uses3_pred <- left_join(centrality_plant2_pred, plant_uses2, by="Genus")
centrality_plant2_fol <- centrality_plant_fol %>% rename("Genus"="Node")
plant_uses3_fol <- left_join(centrality_plant2_fol, plant_uses2, by="Genus")

#correlation tests
disp_multi <- cor.test(log(plant_uses3$PageRank[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"]), plant_uses3$Humans_use[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"])
disp_primary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"])
disp_secondary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"])

pred_multi <- cor.test(log(plant_uses3_pred$PageRank[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"]), plant_uses3_pred$Humans_use[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"])
pred_primary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"])
pred_secondary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"])

fol_multi_secondary <- cor.test(log(plant_uses3_fol$PageRank[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"]), plant_uses3_fol$Humans_use[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"])
fol_primary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"])
fol_secondary <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"])

disp_multi90 <- cor.test(log(plant_uses3$PageRank[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"]), plant_uses3$Humans_use[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"], conf.level = 0.90)
disp_primary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"], conf.level = 0.90)
disp_secondary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"], conf.level = 0.90)

pred_multi90 <- cor.test(log(plant_uses3_pred$PageRank[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"]), plant_uses3_pred$Humans_use[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"], conf.level = 0.90)
pred_primary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"], conf.level = 0.90)
pred_secondary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"], conf.level = 0.90)

fol_multi_secondary90 <- cor.test(log(plant_uses3_fol$PageRank[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"]), plant_uses3_fol$Humans_use[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"], conf.level = 0.90)
fol_primary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"], conf.level = 0.90)
fol_secondary90 <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$Humans_use[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"], conf.level = 0.90)



#correlation tests
disp_multi_sum <- cor.test(log(plant_uses3$PageRank[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"]), plant_uses3$UseSum[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"])
disp_primary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"])
disp_secondary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"])

pred_multi_sum <- cor.test(log(plant_uses3_pred$PageRank[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"]), plant_uses3_pred$UseSum[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"])
pred_primary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"])
pred_secondary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"])

fol_multi_secondary_sum <- cor.test(log(plant_uses3_fol$PageRank[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"]), plant_uses3_fol$UseSum[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"])
fol_primary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"])
fol_secondary_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"])

disp_multi90_sum <- cor.test(log(plant_uses3$PageRank[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"]), plant_uses3$UseSum[plant_uses3$Habitat=="Multilayer"&plant_uses3$Interaction=="Dispersal"], conf.level = 0.90)
disp_primary90_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Dispersal"], conf.level = 0.90)
disp_secondary90_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Dispersal"], conf.level = 0.90)

pred_multi90_sum <- cor.test(log(plant_uses3_pred$PageRank[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"]), plant_uses3_pred$UseSum[plant_uses3_pred$Habitat=="Multilayer"&plant_uses3_pred$Interaction=="Predation"], conf.level = 0.90)
pred_primary90_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Predation"], conf.level = 0.90)
pred_secondary90_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Predation"], conf.level = 0.90)

fol_multi_secondary90_sum <- cor.test(log(plant_uses3_fol$PageRank[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"]), plant_uses3_fol$UseSum[plant_uses3_fol$Habitat=="Multilayer"&plant_uses3_fol$Interaction=="Folivory"], conf.level = 0.90)
fol_primary90_sum<- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="Primary"&plant_uses_prim$Interaction=="Folivory"], conf.level = 0.90)
fol_secondary90_sum <- cor.test(log(plant_uses_prim$PageRank[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"]), plant_uses_prim$UseSum[plant_uses_prim$Habitat=="secondary"&plant_uses_prim$Interaction=="Folivory"], conf.level = 0.90)


#dataframe compilation
disp_multi2 <- c(disp_multi$estimate, disp_multi$conf.int[1], disp_multi$conf.int[2])
disp_primary2 <- c(disp_primary$estimate, disp_primary$conf.int[1], disp_primary$conf.int[2])
disp_secondary2 <- c(disp_secondary$estimate, disp_secondary$conf.int[1], disp_secondary$conf.int[2])

pred_multi2 <- c(pred_multi$estimate, pred_multi$conf.int[1], pred_multi$conf.int[2])
pred_primary2 <- c(pred_primary$estimate, pred_primary$conf.int[1], pred_primary$conf.int[2])
pred_secondary2 <- c(pred_secondary$estimate, pred_secondary$conf.int[1], pred_secondary$conf.int[2])

fol_multi2 <- c(fol_multi_secondary$estimate, fol_multi_secondary$conf.int[1], fol_multi_secondary$conf.int[2])
fol_primary2 <- c(fol_primary$estimate, fol_primary$conf.int[1], fol_primary$conf.int[2])
fol_secondary2 <- c(fol_secondary$estimate, fol_secondary$conf.int[1], fol_secondary$conf.int[2])

disp_multi902 <- c(disp_multi90$estimate, disp_multi90$conf.int[1], disp_multi90$conf.int[2])
disp_primary902 <- c(disp_primary90$estimate, disp_primary90$conf.int[1], disp_primary90$conf.int[2])
disp_secondary902 <- c(disp_secondary90$estimate, disp_secondary90$conf.int[1], disp_secondary90$conf.int[2])

pred_multi902 <- c(pred_multi90$estimate, pred_multi90$conf.int[1], pred_multi90$conf.int[2])
pred_primary902 <- c(pred_primary90$estimate, pred_primary90$conf.int[1], pred_primary90$conf.int[2])
pred_secondary902 <- c(pred_secondary90$estimate, pred_secondary90$conf.int[1], pred_secondary90$conf.int[2])

fol_multi902 <- c(fol_multi_secondary90$estimate, fol_multi_secondary90$conf.int[1], fol_multi_secondary90$conf.int[2])
fol_primary902 <- c(fol_primary90$estimate, fol_primary90$conf.int[1], fol_primary90$conf.int[2])
fol_secondary902 <- c(fol_secondary90$estimate, fol_secondary90$conf.int[1], fol_secondary90$conf.int[2])

human_use_cor <- as.data.frame(rbind(disp_multi2,disp_primary2, disp_secondary2, pred_multi2, pred_primary2, pred_secondary2,  fol_multi2,fol_primary2, fol_secondary2))
colnames(human_use_cor) <- c("Estimate", "Lower", "Upper")
human_use_cor90 <- as.data.frame(rbind(disp_multi902, disp_primary902, disp_secondary902, pred_multi902, pred_primary902, pred_secondary902,fol_multi902, fol_primary902, fol_secondary902))
colnames(human_use_cor90) <- c("Estimate90", "Lower90", "Upper90")
human_use_cor$Interaction <- c("Dispersal","Dispersal",  "Dispersal", "Predation", "Predation", "Predation", "Folivory", "Folivory", "Folivory")
human_use_cor$Habitat <- c("Multilayer","Primary", "Secondary","Multilayer", "Primary", "Secondary","Multilayer", "Primary", "Secondary" )
human_use_cor <- cbind(human_use_cor, human_use_cor90)



#dataframe compilation
disp_multi2_sum <- c(disp_multi_sum$estimate, disp_multi_sum$conf.int[1], disp_multi_sum$conf.int[2])
disp_primary2_sum <- c(disp_primary_sum$estimate, disp_primary_sum$conf.int[1], disp_primary_sum$conf.int[2])
disp_secondary2_sum <- c(disp_secondary_sum$estimate, disp_secondary_sum$conf.int[1], disp_secondary_sum$conf.int[2])

pred_multi2_sum <- c(pred_multi_sum$estimate, pred_multi_sum$conf.int[1], pred_multi_sum$conf.int[2])
pred_primary2_sum <- c(pred_primary_sum$estimate, pred_primary_sum$conf.int[1], pred_primary_sum$conf.int[2])
pred_secondary2_sum <- c(pred_secondary_sum$estimate, pred_secondary_sum$conf.int[1], pred_secondary_sum$conf.int[2])

fol_multi2_sum <- c(fol_multi_secondary_sum$estimate, fol_multi_secondary_sum$conf.int[1], fol_multi_secondary_sum$conf.int[2])
fol_primary2_sum <- c(fol_primary_sum$estimate, fol_primary_sum$conf.int[1], fol_primary_sum$conf.int[2])
fol_secondary2_sum <- c(fol_secondary_sum$estimate, fol_secondary_sum$conf.int[1], fol_secondary_sum$conf.int[2])

disp_multi902_sum <- c(disp_multi90_sum$estimate, disp_multi90_sum$conf.int[1], disp_multi90_sum$conf.int[2])
disp_primary902_sum <- c(disp_primary90_sum$estimate, disp_primary90_sum$conf.int[1], disp_primary90_sum$conf.int[2])
disp_secondary902_sum <- c(disp_secondary90_sum$estimate, disp_secondary90_sum$conf.int[1], disp_secondary90_sum$conf.int[2])

pred_multi902_sum <- c(pred_multi90_sum$estimate, pred_multi90_sum$conf.int[1], pred_multi90_sum$conf.int[2])
pred_primary902_sum <- c(pred_primary90_sum$estimate, pred_primary90_sum$conf.int[1], pred_primary90_sum$conf.int[2])
pred_secondary902_sum <- c(pred_secondary90_sum$estimate, pred_secondary90_sum$conf.int[1], pred_secondary90_sum$conf.int[2])

fol_multi902_sum <- c(fol_multi_secondary90_sum$estimate, fol_multi_secondary90_sum$conf.int[1], fol_multi_secondary90_sum$conf.int[2])
fol_primary902_sum <- c(fol_primary90_sum$estimate, fol_primary90_sum$conf.int[1], fol_primary90_sum$conf.int[2])
fol_secondary902_sum <- c(fol_secondary90_sum$estimate, fol_secondary90_sum$conf.int[1], fol_secondary90_sum$conf.int[2])

human_use_cor_sum <- as.data.frame(rbind(disp_multi2_sum,disp_primary2_sum, disp_secondary2_sum, pred_multi2_sum, pred_primary2_sum, pred_secondary2_sum,  fol_multi2_sum,fol_primary2_sum, fol_secondary2_sum))
colnames(human_use_cor_sum) <- c("Estimate", "Lower", "Upper")
human_use_cor90_sum <- as.data.frame(rbind(disp_multi902_sum, disp_primary902_sum, disp_secondary902_sum, pred_multi902_sum, pred_primary902_sum, pred_secondary902_sum,fol_multi902_sum, fol_primary902_sum, fol_secondary902_sum))
colnames(human_use_cor90_sum) <- c("Estimate90", "Lower90", "Upper90")
human_use_cor_sum$Interaction <- c("Dispersal","Dispersal",  "Dispersal", "Predation", "Predation", "Predation", "Folivory", "Folivory", "Folivory")
human_use_cor_sum$Habitat <- c("Multilayer","Primary", "Secondary","Multilayer", "Primary", "Secondary","Multilayer", "Primary", "Secondary" )
human_use_cor_sum <- cbind(human_use_cor_sum, human_use_cor90_sum)


#plotting
human_use_cor$Interaction <- factor(human_use_cor$Interaction, levels = c("Dispersal", "Predation", "Folivory"))

human_use_plot <- ggplot(data=human_use_cor, aes(x= Interaction, y= Estimate, ymin=Lower, ymax=Upper, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.4), size=1, lwd=0.7)+
  geom_linerange(aes(x= Interaction, y= Estimate, ymin=Lower90, ymax=Upper90, color=Habitat), position = position_dodge(0.4), linewidth=1.8)+
  theme_classic()+
  ylab("Correlation")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"), name ="Land Use Type")+
  theme(legend.position="top")

human_use_cor_sum$Interaction <- factor(human_use_cor_sum$Interaction, levels = c("Dispersal", "Predation", "Folivory"))

human_use_plot_sum <- ggplot(data=human_use_cor_sum, aes(x= Interaction, y= Estimate, ymin=Lower, ymax=Upper, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.4), size=1, lwd=0.7)+
  geom_linerange(aes(x= Interaction, y= Estimate, ymin=Lower90, ymax=Upper90, color=Habitat), position = position_dodge(0.4), linewidth=1.8)+
  theme_classic()+
  ylab("Correlation")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"), name ="Land Use Type")+
  theme(legend.position="top")

ggarrange(human_use_plot, human_use_plot_sum, common.legend = TRUE, labels = c("a", "b"))

```

```{r Plant Traits: Ecological}
#PLANT FUNCTIONAL TRAITS

#Fruit Lengths
centrality_multi_plant_ft <- centrality_multi_plant %>% rename(Genus=Node)
centrality_multi_plant_ft2 <- left_join(centrality_multi_plant_ft, fruit_lengths, by="Genus")
centrality_single_plant2 <- centrality_single_plant %>% rename(Genus=Node)
centrality_plant_single_ft2 <- left_join(centrality_single_plant2, fruit_lengths, by="Genus")

centrality_plant_ft2 <- left_join(centrality_multi_plant_ft2, tree_size, by="Genus")
centrality_plant_single_ft2 <- left_join(centrality_plant_single_ft2, tree_size, by="Genus")


centrality_plant_ft2 <- left_join(centrality_plant_ft2, wood_density, by="Genus")
centrality_plant_single_ft2 <- left_join(centrality_plant_single_ft2, wood_density, by="Genus")

endemism <- plant_names %>% dplyr::select(Genus, Endemic)%>% distinct()%>%drop_na()

centrality_plant_single_ft2

endemism <- endemism %>% dplyr::select(Genus, Endemic) %>% distinct()

centrality_plant_ft2 <- left_join(centrality_plant_ft2, endemism, by ="Genus")
centrality_plant_ft2 <- left_join(centrality_plant_ft2, seed_mass, by ="Genus")

centrality_plant_ft2 <- centrality_plant_ft2 %>% filter(Genus != "sp10") %>% filter(Genus!="Akomba",Genus!="Tongono",Genus!="Simpona",Genus!="Fotsife",Genus!="Fitsidika",Genus!="Tsidy",Genus!="Tsitsihy",Genus!="Kandrandra", Genus!="Bokombolo")

centrality_plant_single_ft2 <- centrality_plant_single_ft2 %>% filter(Genus != "sp10")

centrality_plant_single_ft2 <- left_join(centrality_plant_single_ft2, endemism, by ="Genus")%>% filter(Genus!="Akomba",Genus!="Tongono",Genus!="Simpona",Genus!="Fotsife",Genus!="Fitsidika",Genus!="Tsidy",Genus!="Tsitsihy",Genus!="Kandrandra", Genus!="Bokombolo")
centrality_plant_single_ft2 <-left_join(centrality_plant_single_ft2 , seed_mass, by ="Genus")

```

```{r PGLS Human Use}

pgls_function_human <- function(data, interaction, habitat){
  
plant_trait_data <- data[data$Interaction==interaction&data$Habitat==habitat,] %>% drop_na(Humans_use) %>% filter(Genus !="Plagioscyphus")
  
plants <- plant_trait_data %>% dplyr::select(Genus, Family) %>% distinct()
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% dplyr::select(species, genus, family)
y <- phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3
#tree_plants$tip.label <- gsub("_sp", "", tree_plants$tip.label)
#plot(tree_plants)

length(unique(tree_plants$tip.label))
tree_plants$node.label <- NULL

plant_trait_data$Binomial <- paste0(plant_trait_data $Genus,"_sp")

plant_trait_data <- as.data.frame(plant_trait_data)

plant_trait_data_comp <- caper::comparative.data(phy = tree_plants, data = plant_trait_data , names.col = Binomial, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

model.pgls <- pgls(log(PageRank)~ Humans_use, data = plant_trait_data_comp, lambda
='ML')
return(summary(model.pgls))

ms1 <- dredge(model.pgls)
ms1_summary <- summary(model.avg(get.models(ms1,subset=TRUE ))) 
return(as.data.frame(ms1_summary$coefmat.full))
#plot(ms1)
}

plant_uses3

plant_families <- centrality_plant_single_ft2 %>% dplyr::select(Genus, Family)%>%distinct()

plant_uses4 <- left_join(plant_uses3, plant_families, by = "Genus")
plant_uses4_pred <- left_join(plant_uses3_pred, plant_families, by = "Genus")
plant_uses4_fol <- left_join(plant_uses3_fol, plant_families, by = "Genus")

plant_uses5 <- left_join(plant_uses_prim, plant_families, by = "Genus")

pgls_disp_mult_use <- pgls_function_human(plant_uses4, "Dispersal", "Multilayer")
pgls_pred_mult_use <- pgls_function_human(plant_uses4_pred,"Predation", "Multilayer")
pgls_fol_mult_use <- pgls_function_human(plant_uses4_fol,"Folivory", "Multilayer")

pgls_disp_prim_use <- pgls_function_human(plant_uses5, "Dispersal", "Primary")
pgls_disp_sec_use <- pgls_function_human(plant_uses5,"Dispersal", "secondary")

pgls_pred_prim_use <- pgls_function_human(plant_uses5,"Predation", "Primary")
pgls_pred_sec_use <- pgls_function_human(plant_uses5,"Predation", "secondary")

pgls_fol_prim_use <- pgls_function_human(plant_uses5,"Folivory", "Primary")
pgls_fol_sec_use <- pgls_function_human(plant_uses5,"Folivory", "secondary")



#human use richness

pgls_function_human_rich <- function(data, interaction, habitat){
  
plant_trait_data <- data[data$Interaction==interaction&data$Habitat==habitat,] %>% drop_na(Humans_use) %>% filter(Genus !="Plagioscyphus")
  
plants <- plant_trait_data %>% dplyr::select(Genus, Family) %>% distinct()
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% dplyr::select(species, genus, family)
y <- phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3
#tree_plants$tip.label <- gsub("_sp", "", tree_plants$tip.label)
#plot(tree_plants)

length(unique(tree_plants$tip.label))
tree_plants$node.label <- NULL

plant_trait_data$Binomial <- paste0(plant_trait_data $Genus,"_sp")

plant_trait_data <- as.data.frame(plant_trait_data)

plant_trait_data_comp <- caper::comparative.data(phy = tree_plants, data = plant_trait_data , names.col = Binomial, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

model.pgls <- pgls(log(PageRank)~ UseSum, data = plant_trait_data_comp, lambda
='ML')
return(summary(model.pgls))

ms1 <- dredge(model.pgls)
ms1_summary <- summary(model.avg(get.models(ms1,subset=TRUE ))) 
return(as.data.frame(ms1_summary$coefmat.full))
#plot(ms1)
}

pgls_disp_mult_use_rich <- pgls_function_human_rich(plant_uses4, "Dispersal", "Multilayer")
pgls_pred_mult_use_rich <- pgls_function_human_rich(plant_uses4_pred,"Predation", "Multilayer")
pgls_fol_mult_use_rich <- pgls_function_human_rich(plant_uses4_fol,"Folivory", "Multilayer")

pgls_disp_prim_use_rich <- pgls_function_human_rich(plant_uses5, "Dispersal", "Primary")
pgls_disp_sec_use_rich <- pgls_function_human_rich(plant_uses5,"Dispersal", "secondary")

pgls_pred_prim_use_rich <- pgls_function_human_rich(plant_uses5,"Predation", "Primary")
pgls_pred_sec_use_rich <- pgls_function_human_rich(plant_uses5,"Predation", "secondary")

pgls_fol_prim_use_rich <- pgls_function_human_rich(plant_uses5,"Folivory", "Primary")
pgls_fol_sec_use_rich <- pgls_function_human_rich(plant_uses5,"Folivory", "secondary")


```

```{r PGLS Plotting Human Use}
pgls_disp_mult_df_use <- as.data.frame(pgls_disp_mult_use$coefficients)
pgls_pred_mult_df_use <- as.data.frame(pgls_pred_mult_use$coefficients)
pgls_fol_mult_df_use <- as.data.frame(pgls_fol_mult_use$coefficients)

pgls_disp_mult_df_use$Variable <- rownames(pgls_disp_mult_df_use)  
pgls_pred_mult_df_use$Variable <- rownames(pgls_pred_mult_df_use) 
pgls_fol_mult_df_use$Variable <- rownames(pgls_fol_mult_df_use) 

pgls_disp_mult_df_use$Habitat <- "Multilayer"
pgls_disp_mult_df_use$Interaction <- "Dispersal"
pgls_pred_mult_df_use$Habitat <- "Multilayer"
pgls_pred_mult_df_use$Interaction <- "Predation"
pgls_fol_mult_df_use$Habitat <- "Multilayer"
pgls_fol_mult_df_use$Interaction <- "Herbivory"


pgls_disp_prim_df_use <- as.data.frame(pgls_disp_prim_use$coefficients)
pgls_disp_sec_df_use <- as.data.frame(pgls_disp_sec_use$coefficients)
pgls_pred_prim_df_use <- as.data.frame(pgls_pred_prim_use$coefficients)
pgls_pred_sec_df_use <- as.data.frame(pgls_pred_sec_use$coefficients)
pgls_fol_prim_df_use <- as.data.frame(pgls_fol_prim_use$coefficients)
pgls_fol_sec_df_use <- as.data.frame(pgls_fol_sec_use$coefficients)

pgls_disp_prim_df_use$Variable <- rownames(pgls_disp_prim_df_use) 
pgls_disp_sec_df_use$Variable <- rownames(pgls_disp_sec_df_use)  
pgls_pred_prim_df_use$Variable <- rownames(pgls_pred_prim_df_use) 
pgls_pred_sec_df_use$Variable <- rownames(pgls_pred_sec_df_use) 
pgls_fol_prim_df_use$Variable <- rownames(pgls_fol_prim_df_use) 
pgls_fol_sec_df_use$Variable <- rownames(pgls_fol_sec_df_use) 

pgls_disp_prim_df_use$Habitat <- "Primary"
pgls_disp_prim_df_use$Interaction <- "Dispersal"
pgls_disp_sec_df_use$Habitat <- "Secondary"
pgls_disp_sec_df_use$Interaction <- "Dispersal"
pgls_pred_prim_df_use$Habitat <- "Primary"
pgls_pred_prim_df_use$Interaction <- "Predation"
pgls_pred_sec_df_use$Habitat <- "Secondary"
pgls_pred_sec_df_use$Interaction <- "Predation"
pgls_fol_prim_df_use$Habitat <- "Primary"
pgls_fol_prim_df_use$Interaction <- "Herbivory"
pgls_fol_sec_df_use$Habitat <- "Secondary"
pgls_fol_sec_df_use$Interaction <- "Herbivory"

pgls_df_use <- rbind(pgls_disp_mult_df_use, 
                 pgls_pred_mult_df_use,
                 pgls_fol_mult_df_use, 
                 pgls_disp_prim_df_use, pgls_disp_sec_df_use,
                 pgls_pred_prim_df_use, pgls_pred_sec_df_use,
                 pgls_fol_prim_df_use, pgls_fol_sec_df_use)

pgls_df_use$Lower <- pgls_df_use$Estimate - 1.96 * pgls_df_use$`Std. Error`
pgls_df_use$Upper <- pgls_df_use$Estimate + 1.96 * pgls_df_use$`Std. Error`
pgls_df_use$Lower90 <- pgls_df_use$Estimate - 1.644854 * pgls_df_use$`Std. Error`
pgls_df_use$Upper90 <- pgls_df_use$Estimate + 1.644854 * pgls_df_use$`Std. Error`

pgls_df_summary_use <- pgls_df_use

pgls_df_use <- pgls_df_use %>% filter(Variable != "(Intercept)")
pgls_df_use$Variable[pgls_df_use$Variable=="Humans_use"] <- "Human Use Proportion"

pgls_df_use$Interaction<- factor(pgls_df_use$Interaction, levels = c("Dispersal", "Predation", "Herbivory"))

human_use_plot2 <- ggplot(data=pgls_df_use, aes(x=Interaction, y= Estimate, ymin=Lower, ymax=Upper, shape=Variable, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Interaction, y= Estimate, ymin=Lower90, ymax=Upper90,  shape=Variable, color=Habitat), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimate")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"))+
  theme(legend.position="bottom")+
  xlab("Land Use Type")+ 
  theme(legend.position="none")


pgls_disp_mult_df_use_rich <- as.data.frame(pgls_disp_mult_use_rich$coefficients)
pgls_pred_mult_df_use_rich <- as.data.frame(pgls_pred_mult_use_rich$coefficients)
pgls_fol_mult_df_use_rich <- as.data.frame(pgls_fol_mult_use_rich$coefficients)

pgls_disp_mult_df_use_rich$Variable <- rownames(pgls_disp_mult_df_use_rich)  
pgls_pred_mult_df_use_rich$Variable <- rownames(pgls_pred_mult_df_use_rich) 
pgls_fol_mult_df_use_rich$Variable <- rownames(pgls_fol_mult_df_use_rich) 

pgls_disp_mult_df_use_rich$Habitat <- "Multilayer"
pgls_disp_mult_df_use_rich$Interaction <- "Dispersal"
pgls_pred_mult_df_use_rich$Habitat <- "Multilayer"
pgls_pred_mult_df_use_rich$Interaction <- "Predation"
pgls_fol_mult_df_use_rich$Habitat <- "Multilayer"
pgls_fol_mult_df_use_rich$Interaction <- "Herbivory"


pgls_disp_prim_df_use_rich <- as.data.frame(pgls_disp_prim_use_rich$coefficients)
pgls_disp_sec_df_use_rich <- as.data.frame(pgls_disp_sec_use_rich$coefficients)
pgls_pred_prim_df_use_rich <- as.data.frame(pgls_pred_prim_use_rich$coefficients)
pgls_pred_sec_df_use_rich <- as.data.frame(pgls_pred_sec_use_rich$coefficients)
pgls_fol_prim_df_use_rich <- as.data.frame(pgls_fol_prim_use_rich$coefficients)
pgls_fol_sec_df_use_rich <- as.data.frame(pgls_fol_sec_use_rich$coefficients)

pgls_disp_prim_df_use_rich$Variable <- rownames(pgls_disp_prim_df_use_rich) 
pgls_disp_sec_df_use_rich$Variable <- rownames(pgls_disp_sec_df_use_rich)  
pgls_pred_prim_df_use_rich$Variable <- rownames(pgls_pred_prim_df_use_rich) 
pgls_pred_sec_df_use_rich$Variable <- rownames(pgls_pred_sec_df_use_rich) 
pgls_fol_prim_df_use_rich$Variable <- rownames(pgls_fol_prim_df_use_rich) 
pgls_fol_sec_df_use_rich$Variable <- rownames(pgls_fol_sec_df_use_rich) 

pgls_disp_prim_df_use_rich$Habitat <- "Primary"
pgls_disp_prim_df_use_rich$Interaction <- "Dispersal"
pgls_disp_sec_df_use_rich$Habitat <- "Secondary"
pgls_disp_sec_df_use_rich$Interaction <- "Dispersal"
pgls_pred_prim_df_use_rich$Habitat <- "Primary"
pgls_pred_prim_df_use_rich$Interaction <- "Predation"
pgls_pred_sec_df_use_rich$Habitat <- "Secondary"
pgls_pred_sec_df_use_rich$Interaction <- "Predation"
pgls_fol_prim_df_use_rich$Habitat <- "Primary"
pgls_fol_prim_df_use_rich$Interaction <- "Herbivory"
pgls_fol_sec_df_use_rich$Habitat <- "Secondary"
pgls_fol_sec_df_use_rich$Interaction <- "Herbivory"

pgls_df_use_rich <- rbind(pgls_disp_mult_df_use_rich, 
                 pgls_pred_mult_df_use_rich,
                 pgls_fol_mult_df_use_rich, 
                 pgls_disp_prim_df_use_rich, pgls_disp_sec_df_use_rich,
                 pgls_pred_prim_df_use_rich, pgls_pred_sec_df_use_rich,
                 pgls_fol_prim_df_use_rich, pgls_fol_sec_df_use_rich)

pgls_df_use_rich$Lower <- pgls_df_use_rich$Estimate - 1.96 * pgls_df_use_rich$`Std. Error`
pgls_df_use_rich$Upper <- pgls_df_use_rich$Estimate + 1.96 * pgls_df_use_rich$`Std. Error`
pgls_df_use_rich$Lower90 <- pgls_df_use_rich$Estimate - 1.644854 * pgls_df_use_rich$`Std. Error`
pgls_df_use_rich$Upper90 <- pgls_df_use_rich$Estimate + 1.644854 * pgls_df_use_rich$`Std. Error`

pgls_df_summary_use_rich <- pgls_df_use_rich

pgls_df_use_rich <- pgls_df_use_rich %>% filter(Variable != "(Intercept)")
pgls_df_use_rich$Variable[pgls_df_use_rich$Variable=="UseSum"] <- "Human Use Sum"
pgls_df_use_rich$Interaction<- factor(pgls_df_use_rich$Interaction, levels = c("Dispersal", "Predation", "Herbivory"))

human_use_rich_plot2 <- ggplot(data=pgls_df_use_rich, aes(x=Interaction, y= Estimate, ymin=Lower, ymax=Upper, shape=Variable, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Interaction, y= Estimate, ymin=Lower90, ymax=Upper90,  shape=Variable, color=Habitat), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimate")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"))+
  theme(legend.position="bottom")+
  xlab("Land Use Type")+ 
  theme(legend.position="none")

ggarrange(human_use_plot2, human_use_rich_plot2,labels = c("a", "b"))


pgls_df_use2 <- rbind(pgls_df_use, pgls_df_use_rich) %>% dplyr::select(Habitat, Interaction, Variable, Estimate, Lower, Upper, `Pr(>|t|)`)
pgls_df_use2 <- pgls_df_use2[order(pgls_df_use2$Interaction), ]
pgls_df_use2 <- pgls_df_use2[order(pgls_df_use2$Habitat), ]
pgls_df_use2 <- pgls_df_use2[order(pgls_df_use2$Variable), ]
pgls_df_use2$Estimate <- round(pgls_df_use2$Estimate, 3)
pgls_df_use2$Lower <- round(pgls_df_use2$Lower, 3)
pgls_df_use2$Upper <- round(pgls_df_use2$Upper, 3)
pgls_df_use2$`Pr(>|t|)` <- round(pgls_df_use2$`Pr(>|t|)`, 3)

write.csv(pgls_df_use2, file=paste0(save_path, "pgls_df_use.csv"))

```

```{r PGLS Functional}

pgls_function <- function(data, interaction, habitat){
  
plant_trait_data <- data[data$Interaction==interaction&data$Habitat==habitat,]
  
plants <- plant_trait_data %>% dplyr::select(Genus, Family) %>% distinct()
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% dplyr::select(species, genus, family)
y <- phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3


length(unique(tree_plants$tip.label))
tree_plants$node.label <- NULL

plant_trait_data $Binomial <- paste0(plant_trait_data $Genus,"_sp")
plant_trait_data_comp <- caper::comparative.data(phy = tree_plants, data = plant_trait_data , names.col = Binomial, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

model.pgls <- pgls(log(PageRank)~ FruitLength + DBH + meanWD + Endemic, data = plant_trait_data_comp, lambda
='ML')
return(summary(model.pgls))

ms1 <- dredge(model.pgls)
ms1_summary <- summary(model.avg(get.models(ms1,subset=TRUE ))) 
return(as.data.frame(ms1_summary$coefmat.full))
#plot(ms1)
}




pgls_function_pred <- function(data, interaction, habitat){
  
plant_trait_data <- data[data$Interaction==interaction&data$Habitat==habitat,]
  
plants <- plant_trait_data %>% dplyr::select(Genus, Family) %>% distinct()
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% dplyr::select(species, genus, family)
y <- phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3
#tree_plants$tip.label <- gsub("_sp", "", tree_plants$tip.label)
#plot(tree_plants)

length(unique(tree_plants$tip.label))
tree_plants$node.label <- NULL

plant_trait_data $Binomial <- paste0(plant_trait_data $Genus,"_sp")
plant_trait_data_comp <- caper::comparative.data(phy = tree_plants, data = plant_trait_data , names.col = Binomial, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

model.pgls <- pgls(log(PageRank)~ mass + DBH + meanWD + Endemic, data = plant_trait_data_comp, lambda
='ML')
return(summary(model.pgls))

ms1 <- dredge(model.pgls)
ms1_summary <- summary(model.avg(get.models(ms1,subset=TRUE ))) 
return(as.data.frame(ms1_summary$coefmat.full))
#plot(ms1)
}



pgls_function_fol <- function(data, interaction, habitat){
  
plant_trait_data <- data[data$Interaction==interaction&data$Habitat==habitat,]
  
plants <- plant_trait_data %>% dplyr::select(Genus, Family) %>% distinct()
colnames(plants) <- c("genus", "family")
plants$species <- plants$genus
plants$spp <- "sp"
plants <- unite(data=plants, "species", species, spp, sep = " ")
plants <- plants %>% dplyr::select(species, genus, family)
y <- phylo.maker(plants, scenarios = "S3") # default scenario
tree_plants <- y$scenario.3
#tree_plants$tip.label <- gsub("_sp", "", tree_plants$tip.label)
#plot(tree_plants)

length(unique(tree_plants$tip.label))
tree_plants$node.label <- NULL

tree2 <- read.tree("~/Downloads/TreePL_mada_gen_03012024.tre")

plant_trait_data$Binomial <- paste0(plant_trait_data$Genus,"_sp")
plant_trait_data_comp <- caper::comparative.data(phy = tree_plants, data = plant_trait_data, names.col = Binomial, vcv = TRUE, na.omit = FALSE, warn.dropped = TRUE)

model.pgls <- pgls(log(PageRank)~ meanWD + Endemic + DBH, data = plant_trait_data_comp, lambda
='ML')
return(summary(model.pgls))

ms1 <- dredge(model.pgls)
ms1_summary <- summary(model.avg(get.models(ms1,subset=TRUE ))) 
return(as.data.frame(ms1_summary$coefmat.full))
#plot(ms1)
}


pgls_disp_mult <- pgls_function(centrality_plant_ft2, "Dispersal", "Multilayer") #0.0, small signal
pgls_pred_mult <- pgls_function_pred(centrality_plant_ft2,"Predation", "Multilayer") #0.211
pgls_fol_mult <- pgls_function_fol(centrality_plant_ft2,"Folivory", "Multilayer")#0.575

pgls_disp_prim <- pgls_function(centrality_plant_single_ft2, "Dispersal", "Primary")#0.0
pgls_disp_sec <- pgls_function(centrality_plant_single_ft2,"Dispersal", "secondary")#0.0

pgls_pred_prim <- pgls_function_pred(centrality_plant_single_ft2,"Predation", "Primary")#0.0
pgls_pred_sec <- pgls_function_pred(centrality_plant_single_ft2,"Predation", "secondary")#1

pgls_fol_prim <- pgls_function_fol(centrality_plant_single_ft2,"Folivory", "Primary")#0
pgls_fol_sec <- pgls_function_fol(centrality_plant_single_ft2,"Folivory", "secondary")#0.0





```

```{r PGLS Plotting}
pgls_disp_mult_df <- as.data.frame(pgls_disp_mult$coefficients)
pgls_pred_mult_df <- as.data.frame(pgls_pred_mult$coefficients)
pgls_fol_mult_df <- as.data.frame(pgls_fol_mult$coefficients)

pgls_disp_mult_df$Variable <- rownames(pgls_disp_mult_df)  
pgls_pred_mult_df$Variable <- rownames(pgls_pred_mult_df) 
pgls_fol_mult_df$Variable <- rownames(pgls_fol_mult_df) 

pgls_disp_mult_df$Habitat <- "Multilayer"
pgls_disp_mult_df$Interaction <- "Dispersal"
pgls_pred_mult_df$Habitat <- "Multilayer"
pgls_pred_mult_df$Interaction <- "Predation"
pgls_fol_mult_df$Habitat <- "Multilayer"
pgls_fol_mult_df$Interaction <- "Herbivory"


pgls_disp_prim_df <- as.data.frame(pgls_disp_prim$coefficients)
pgls_disp_sec_df <- as.data.frame(pgls_disp_sec$coefficients)
pgls_pred_prim_df <- as.data.frame(pgls_pred_prim$coefficients)
pgls_pred_sec_df <- as.data.frame(pgls_pred_sec$coefficients)
pgls_fol_prim_df <- as.data.frame(pgls_fol_prim$coefficients)
pgls_fol_sec_df <- as.data.frame(pgls_fol_sec$coefficients)

pgls_disp_prim_df$Variable <- rownames(pgls_disp_prim_df) 
pgls_disp_sec_df$Variable <- rownames(pgls_disp_sec_df)  
pgls_pred_prim_df$Variable <- rownames(pgls_pred_prim_df) 
pgls_pred_sec_df$Variable <- rownames(pgls_pred_sec_df) 
pgls_fol_prim_df$Variable <- rownames(pgls_fol_prim_df) 
pgls_fol_sec_df$Variable <- rownames(pgls_fol_sec_df) 

pgls_disp_prim_df$Habitat <- "Primary"
pgls_disp_prim_df$Interaction <- "Dispersal"
pgls_disp_sec_df$Habitat <- "Secondary"
pgls_disp_sec_df$Interaction <- "Dispersal"
pgls_pred_prim_df$Habitat <- "Primary"
pgls_pred_prim_df$Interaction <- "Predation"
pgls_pred_sec_df$Habitat <- "Secondary"
pgls_pred_sec_df$Interaction <- "Predation"
pgls_fol_prim_df$Habitat <- "Primary"
pgls_fol_prim_df$Interaction <- "Herbivory"
pgls_fol_sec_df$Habitat <- "Secondary"
pgls_fol_sec_df$Interaction <- "Herbivory"

pgls_df <- rbind(pgls_disp_mult_df, 
                 pgls_pred_mult_df,
                 pgls_fol_mult_df, 
                 pgls_disp_prim_df, pgls_disp_sec_df,
                 pgls_pred_prim_df, pgls_pred_sec_df,
                 pgls_fol_prim_df, pgls_fol_sec_df)

pgls_df$Lower <- pgls_df$Estimate - 1.96 * pgls_df$`Std. Error`
pgls_df$Upper <- pgls_df$Estimate + 1.96 * pgls_df$`Std. Error`
pgls_df$Lower90 <- pgls_df$Estimate - 1.644854 * pgls_df$`Std. Error`
pgls_df$Upper90 <- pgls_df$Estimate + 1.644854 * pgls_df$`Std. Error`

pgls_df_summary <- pgls_df

pgls_df <- pgls_df %>% filter(Variable != "(Intercept)")
pgls_df$Variable[pgls_df$Variable=="EndemicYes"] <- "Endemic"
pgls_df$Variable[pgls_df$Variable=="meanWD"] <- "WD"
pgls_df$Variable[pgls_df$Variable=="FruitLength"] <- "Fruit Length"
pgls_df$Variable[pgls_df$Variable=="mass"] <- "Seed Mass"

dispersal_functional_plot <- ggplot(data=pgls_df[pgls_df$Interaction=="Dispersal",], aes(x=Habitat, y= Estimate, ymin=Lower, ymax=Upper, shape=Variable, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Habitat, y= Estimate, ymin=Lower90, ymax=Upper90,  shape=Variable, color=Habitat), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimate")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"))+
  scale_shape_manual(values=c(19,15, 17,18),name = NULL)+ guides(color = FALSE, alpha=FALSE)+
  theme(legend.position="bottom")+
  xlab("Land Use Type")

predation_functional_plot <- ggplot(data=pgls_df[pgls_df$Interaction=="Predation",], aes(x=Habitat, y= Estimate, ymin=Lower, ymax=Upper, shape=Variable, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Habitat, y= Estimate, ymin=Lower90, ymax=Upper90,  shape=Variable, color=Habitat), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimate")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"))+
  scale_shape_manual(values=c(19,15, 8,18),name = NULL)+ guides(color = FALSE, alpha=FALSE)+
  theme(legend.position="bottom")+
  xlab("Land Use Type")

folivory_functional_plot <- ggplot(data=pgls_df[pgls_df$Interaction=="Herbivory",], aes(x=Habitat, y= Estimate, ymin=Lower, ymax=Upper, shape=Variable, color=Habitat))+
  geom_hline(yintercept = 0, linetype="dashed")+
  geom_pointrange(position = position_dodge(0.5), size=0.7, lwd=0.7)+
  geom_linerange(aes(x= Habitat, y= Estimate, ymin=Lower90, ymax=Upper90,  shape=Variable, color=Habitat), position = position_dodge(0.5), linewidth=1.5)+
  theme_classic()+
  ylab("Estimate")+
  scale_color_manual(values = c("grey", "darkseagreen3", "lightgoldenrod"))+
  scale_shape_manual(values=c(19,15,18),name = NULL)+ guides(color = FALSE, alpha=FALSE)+
  theme(legend.position="bottom")+
  xlab("Land Use Type")

pglm_plot <- ggarrange(dispersal_functional_plot, predation_functional_plot, folivory_functional_plot, ncol=1, labels = c("a", "b", "c"), common.legend = TRUE)

trait_plot <- ggarrange(human_use_plot, pglm_plot, ncol=1, heights = c(1,3), labels = c("a",""))

trait_plot2 <- ggarrange(human_use_plot, dispersal_functional_plot, predation_functional_plot, folivory_functional_plot, labels = c("a","b", "c", "d"))

pgls_df2 <- pgls_df %>% mutate(Estimate= round(Estimate,3), `Std. Error`= round(`Std. Error`,3), `Pr(>|t|)` = round(`Pr(>|t|)`,3)) %>% dplyr::select(Habitat, Interaction, Variable, Estimate, `Std. Error`,`Pr(>|t|)`)

pgls_df2_summary <- pgls_df_summary %>% mutate(Estimate= round(Estimate,3), `Std. Error`= round(`Std. Error`,3), `Pr(>|t|)` = round(`Pr(>|t|)`,3)) %>% dplyr::select(Habitat, Interaction, Variable, Estimate, `Std. Error`,`Pr(>|t|)`)

pgls_df3 <- pgls_df2_summary[order(pgls_df2_summary$Habitat),]

write.csv(pgls_df3, file=paste0(save_path, "pgls_df.csv"))


```

```{r Lambda}
l_disp_prim_mult_df <- as.data.frame(pgls_disp_prim_mult$param.CI$lambda)
l_disp_sec_mult_df <- as.data.frame(pgls_disp_sec_mult$param.CI$lambda)
l_pred_prim_mult_df <- as.data.frame(pgls_pred_prim_mult$param.CI$lambda)
l_pred_sec_mult_df <- as.data.frame(pgls_pred_sec_mult$param.CI$lambda)
l_fol_prim_mult_df <- as.data.frame(pgls_fol_prim_mult$param.CI$lambda)
l_fol_sec_mult_df <- as.data.frame(pgls_fol_sec_mult$param.CI$lambda)
l_disp_prim_df <- as.data.frame(pgls_disp_prim$param.CI$lambda)
l_disp_sec_df <- as.data.frame(pgls_disp_sec$param.CI$lambda)
l_pred_prim_df <- as.data.frame(pgls_pred_prim$param.CI$lambda)
l_pred_sec_df <- as.data.frame(pgls_pred_sec$param.CI$lambda)
l_fol_prim_df <- as.data.frame(pgls_fol_prim$param.CI$lambda)
l_fol_sec_df <- as.data.frame(pgls_fol_sec$param.CI$lambda)

```
